"""The Rook13 rules engine, ported from src/lib/game/engine.ts.

Mutable for speed (training plays millions of hands), but the transitions
mirror applyAction() exactly. tests/test_parity.py replays golden traces
generated by the TS engine and asserts identical states after every action.

Phases: dealing -> (redeal ->) bidding -> widow -> trump -> playing ->
hand_done -> dealing ... -> game_over. Full games run to 500 / -250.
"""

from __future__ import annotations

from .cards import (
    PASS, SEATS, VALID_BIDS, TRICKS_PER_HAND, WIN_SCORE, LOSE_SCORE,
    TAKING_TRICKS_BONUS, card_points, suit_of, num_of, team_of, next_seat,
    split_deal, is_redeal_hand,
)

DEALING = 0
REDEAL = 1
BIDDING = 2
WIDOW = 3
TRUMP = 4
PLAYING = 5
HAND_DONE = 6
GAME_OVER = 7

PHASE_NAMES = ("dealing", "redeal", "bidding", "widow", "trump", "playing",
               "hand_done", "game_over")


def winning_card_seat(plays: list[tuple[int, int]], trump: int | None) -> int:
    """plays = [(seat, card), ...] in play order. Port of winningCardSeat."""
    lead = suit_of(plays[0][1])
    best = plays[0]
    for p in plays[1:]:
        best_is_trump = trump is not None and suit_of(best[1]) == trump
        p_is_trump = trump is not None and suit_of(p[1]) == trump
        if p_is_trump and not best_is_trump:
            best = p
        elif (p_is_trump == best_is_trump and suit_of(p[1]) == suit_of(best[1])
              and num_of(p[1]) > num_of(best[1])):
            best = p
        elif (not p_is_trump and not best_is_trump
              and suit_of(best[1]) != lead and suit_of(p[1]) == lead):
            best = p  # kept for safety, mirrors the TS engine
    return best[0]


def bid_lead(dealer: int) -> int:
    """Seat that opens the bidding / leads trick 1: left of the dealer."""
    return next_seat(dealer)


class Game:
    """Engine state for one full game (lobby/seat management not needed here)."""

    __slots__ = (
        "phase", "hand_number", "dealer", "turn",
        "hands", "widow", "go_down",
        "bids", "high_bid", "bid_winner", "trump",
        "trick_plays", "trick_leader", "completed_tricks",
        "tricks_won", "points_taken", "scores",
        "hand_history", "redeal_seat", "redeal_count", "winner",
        "win_score", "lose_score",
    )

    def __init__(self, dealer: int, win_score: int = WIN_SCORE,
                 lose_score: int = LOSE_SCORE):
        # Family rules are 500/-250; marathon evaluation games (e.g.
        # 2000/-1000) pack ~4x the hands per game, shrinking card luck.
        self.win_score = win_score
        self.lose_score = lose_score
        self.phase = DEALING
        self.hand_number = 1
        self.dealer = dealer
        self.turn: int | None = dealer
        self.hands: list[list[int]] = [[], [], [], []]
        self.widow: list[int] = []
        self.go_down: list[int] = []
        self.bids: list[int | None] = [None, None, None, None]  # None=silent, PASS, or value
        self.high_bid: int | None = None
        self.bid_winner: int | None = None
        self.trump: int | None = None
        self.trick_plays: list[tuple[int, int]] = []
        self.trick_leader: int | None = None
        # completed tricks: (leader, plays, winner, points)
        self.completed_tricks: list[tuple[int, list[tuple[int, int]], int, int]] = []
        self.tricks_won = [0, 0]
        self.points_taken = [0, 0]
        self.scores = [0, 0]
        # (hand_number, bid_winner, bid, trump, score_delta_A, score_delta_B, went_set)
        self.hand_history: list[tuple] = []
        self.redeal_seat: int | None = None
        self.redeal_count = 0
        self.winner: int | None = None

    def clone(self) -> "Game":
        """Independent copy — one level of nesting deep, which is as deep
        as any Game field goes (lists of ints/tuples)."""
        c = Game(dealer=self.dealer, win_score=self.win_score,
                 lose_score=self.lose_score)
        for slot in Game.__slots__:
            v = getattr(self, slot)
            if isinstance(v, list):
                v = [list(x) if isinstance(x, list) else x for x in v]
            setattr(c, slot, v)
        return c

    # --- queries -----------------------------------------------------------

    def lead_suit(self) -> int | None:
        return suit_of(self.trick_plays[0][1]) if self.trick_plays else None

    def legal_cards(self, seat: int) -> list[int]:
        if self.phase != PLAYING or self.turn != seat:
            return []
        hand = self.hands[seat]
        lead = self.lead_suit()
        if lead is None:
            return list(hand)
        followers = [c for c in hand if suit_of(c) == lead]
        return followers if followers else list(hand)

    def min_next_bid(self) -> int | None:
        floor = VALID_BIDS[0] if self.high_bid is None else self.high_bid + 5
        return None if floor > VALID_BIDS[-1] else floor

    def must_bid(self) -> bool:
        if self.phase != BIDDING:
            return False
        passes = sum(1 for b in self.bids if b == PASS)
        return passes == 3 and self.high_bid is None

    def go_down_points(self) -> int:
        return sum(card_points(c) for c in self.go_down)

    # --- transitions (mirror applyAction) -----------------------------------

    def _reset_hand_state(self) -> None:
        self.bids = [None, None, None, None]
        self.high_bid = None
        self.bid_winner = None
        self.trump = None
        self.go_down = []
        self.trick_plays = []
        self.trick_leader = None
        self.completed_tricks = []
        self.tricks_won = [0, 0]
        self.points_taken = [0, 0]

    def deal(self, deck: list[int]) -> None:
        assert self.phase in (DEALING, REDEAL), PHASE_NAMES[self.phase]
        hands, widow = split_deal(deck)
        self.hands = hands
        self.widow = widow
        offender = next((s for s in SEATS if is_redeal_hand(hands[s])), None)
        if offender is not None:
            self.phase = REDEAL
            self.redeal_seat = offender
            self.redeal_count += 1
            self.turn = self.dealer
            return
        self.redeal_seat = None
        self.phase = BIDDING
        self.turn = bid_lead(self.dealer)
        self._reset_hand_state()

    def bid(self, seat: int, bid: int) -> None:
        assert self.phase == BIDDING and self.turn == seat
        if bid != PASS:
            assert bid in VALID_BIDS and (self.high_bid is None or bid > self.high_bid)
        else:
            assert not self.must_bid()
        self.bids[seat] = bid
        if bid != PASS:
            self.high_bid = bid

        passes = sum(1 for b in self.bids if b == PASS)
        maxed_out = self.high_bid == VALID_BIDS[-1]

        if (passes == 3 and self.high_bid is not None) or maxed_out:
            winner = seat if maxed_out else next(s for s in SEATS if self.bids[s] != PASS)
            self.bid_winner = winner
            self.phase = WIDOW
            self.turn = winner
            self.hands[winner] = self.hands[winner] + self.widow
            self.widow = []
            return

        t = next_seat(seat)
        while self.bids[t] == PASS:
            t = next_seat(t)
        self.turn = t

    def select_go_down(self, seat: int, cards: list[int]) -> None:
        assert self.phase == WIDOW and self.bid_winner == seat and len(cards) == 4
        hand = self.hands[seat]
        assert all(c in hand for c in cards) and len(set(cards)) == 4
        self.go_down = list(cards)
        drop = set(cards)
        self.hands[seat] = [c for c in hand if c not in drop]
        self.phase = TRUMP
        self.turn = seat

    def select_trump(self, seat: int, suit: int) -> None:
        assert self.phase == TRUMP and self.bid_winner == seat
        self.trump = suit
        self.phase = PLAYING
        self.trick_leader = bid_lead(self.dealer)
        self.turn = self.trick_leader
        self.trick_plays = []

    def play_card(self, seat: int, card: int) -> None:
        assert self.phase == PLAYING and self.turn == seat
        legal = self.legal_cards(seat)
        assert card in legal, f"illegal card {card} (legal: {legal})"
        self.hands[seat].remove(card)
        self.trick_plays.append((seat, card))

        if len(self.trick_plays) < 4:
            self.turn = next_seat(seat)
            return

        winner = winning_card_seat(self.trick_plays, self.trump)
        points = sum(card_points(c) for _, c in self.trick_plays)
        winning_team = team_of(winner)
        self.completed_tricks.append(
            (self.trick_leader, self.trick_plays, winner, points))
        self.tricks_won[winning_team] += 1
        self.points_taken[winning_team] += points
        self.trick_plays = []
        self.trick_leader = winner
        self.turn = winner

        if len(self.completed_tricks) == TRICKS_PER_HAND:
            self._score_hand(winner)

    def next_hand(self) -> None:
        assert self.phase == HAND_DONE
        self.hand_number += 1
        self.dealer = next_seat(self.dealer)
        self.turn = self.dealer
        self.phase = DEALING
        self.hands = [[], [], [], []]
        self.widow = []
        self._reset_hand_state()
        self.redeal_seat = None

    def _score_hand(self, last_trick_winner: int) -> None:
        gd_points = self.go_down_points()
        points_taken = list(self.points_taken)
        points_taken[team_of(last_trick_winner)] += gd_points
        if self.tricks_won[0] >= 5:
            points_taken[0] += TAKING_TRICKS_BONUS
        if self.tricks_won[1] >= 5:
            points_taken[1] += TAKING_TRICKS_BONUS

        bid_team = team_of(self.bid_winner)
        def_team = 1 - bid_team
        bid = self.high_bid
        went_set = points_taken[bid_team] < bid

        hand_score = [0, 0]
        hand_score[bid_team] = -bid if went_set else points_taken[bid_team]
        hand_score[def_team] = points_taken[def_team]

        self.scores[0] += hand_score[0]
        self.scores[1] += hand_score[1]
        self.hand_history.append(
            (self.hand_number, self.bid_winner, bid, self.trump,
             hand_score[0], hand_score[1], went_set))

        over = (self.scores[0] >= self.win_score or self.scores[1] >= self.win_score
                or self.scores[0] <= self.lose_score or self.scores[1] <= self.lose_score)
        if over and self.scores[0] != self.scores[1]:
            self.winner = 0 if self.scores[0] > self.scores[1] else 1
            self.phase = GAME_OVER
            self.turn = None
        else:
            self.phase = HAND_DONE
            self.turn = None
