// Parity proof: the browser gen7/gen8 bots ARE the trained models.
//
// ml/alpharook/export_web.py dumps the frozen weights (public/models/*.bin)
// plus two fixtures generated by the Python training stack:
//   qnet.golden.json — random (state, action) vectors and their torch q values
//   game.<gen>.json  — one complete seeded game where the net made every bid
//                      and card play at all four seats (go-down/trump by the
//                      family heuristic, exactly how the bots run live)
// This suite re-runs both through the TS engine + encoder + forward pass and
// demands the same numbers and the same decisions. If it passes, what the
// family faces on rook13.com is decision-for-decision the arena champion.
//
// Regenerate fixtures after freezing a new model:
//   cd ml && ~/torch-env/bin/python -m alpharook.export_web

import { describe, it, expect } from 'vitest';
import * as fs from 'fs';
import * as path from 'path';
import { GameDoc, SEATS, SUITS } from '../game/types';
import { createGameDoc, applyAction } from '../game/engine';
import { bestTrumpSuit, chooseGoDown, PERSONALITIES } from '../game/bots';
import { neuralChoice } from './agent';
import { cardToInt, intToCard, suitToInt, D_BID, D_TRUMP, D_DISCARD, D_PLAY, PASS } from './encoder';
import { parseWeights, qForward, QNetWeights } from './qnet';

const ROOT = path.resolve(__dirname, '../../..');

const loadWeights = (gen: string): QNetWeights => {
    const buf = fs.readFileSync(path.join(ROOT, 'public/models', `${gen}.bin`));
    return parseWeights(buf.buffer.slice(buf.byteOffset, buf.byteOffset + buf.byteLength));
};

const loadFixture = <T>(name: string): T =>
    JSON.parse(fs.readFileSync(path.join(__dirname, '__fixtures__', name), 'utf8')) as T;

// float32 op-reorder noise between torch and our f64-accumulating matmul;
// q targets live in roughly [-1, 1], so this is a tight bound
const Q_TOL = 2e-3;

interface GoldenFixture {
    state_dim: number;
    action_dim: number;
    states: number[][];
    actions: number[][];
    q: Record<string, number[]>;
}

interface GameStep {
    seat: number;
    dtype: number;
    cands: number[];
    q?: number[];
    chosen: number;
    neural: boolean;
}

interface GameFixture {
    gen: string;
    dealer: number;
    decks: number[][];
    steps: GameStep[];
    finalScores: number[];
    handsPlayed: number;
}

const GENS = ['gen7', 'gen8'] as const;

describe('QNet forward pass matches torch', () => {
    const golden = loadFixture<GoldenFixture>('qnet.golden.json');

    for (const gen of GENS) {
        it(`${gen} reproduces the golden vectors`, () => {
            const net = loadWeights(gen);
            for (let i = 0; i < golden.states.length; i++) {
                const q = qForward(net, Float32Array.from(golden.states[i]), Float32Array.from(golden.actions[i]));
                expect(Math.abs(q - golden.q[gen][i])).toBeLessThan(Q_TOL);
            }
        });
    }
});

describe('full-game decision parity with the training arena', () => {
    for (const gen of GENS) {
        it(`${gen} replays its Python-traced game move for move`, () => {
            const net = loadWeights(gen);
            const f = loadFixture<GameFixture>(`game.${gen}.json`);

            let g: GameDoc = createGameDoc({
                id: `parity-${gen}`, joinCode: '0000',
                host: { uid: 'parity', name: 'parity' }, now: 0,
            });
            for (const s of SEATS) g.seats[s] = { kind: 'bot', name: s, botStyle: gen };
            g.status = 'active';
            g.phase = 'dealing';
            g.handNumber = 1;
            g.dealer = SEATS[f.dealer];
            g.turn = g.dealer;

            let deckIdx = 0;
            let stepIdx = 0;
            const nextStep = (): GameStep => {
                expect(stepIdx, 'fixture ran out of steps').toBeLessThan(f.steps.length);
                return f.steps[stepIdx++];
            };
            let safety = 20000;
            while (g.phase !== 'game_over' && safety-- > 0) {
                const phase: string = g.phase;
                if (phase === 'dealing' || phase === 'redeal') {
                    const deck = f.decks[deckIdx++].map(intToCard);
                    g = applyAction(g, phase === 'dealing' ? { type: 'DEAL', deck } : { type: 'ACK_REDEAL', deck }, 0);
                } else if (phase === 'hand_done') {
                    g = applyAction(g, { type: 'NEXT_HAND' }, 0);
                } else if (phase === 'bidding' || phase === 'playing') {
                    const step = nextStep();
                    const seat = g.turn!;
                    expect(SEATS[step.seat]).toBe(seat);
                    expect(step.dtype).toBe(phase === 'bidding' ? D_BID : D_PLAY);

                    const d = neuralChoice(g, seat, net)!;
                    expect(d.cands).toEqual(step.cands);
                    for (let i = 0; i < d.q.length; i++) {
                        expect(Math.abs(d.q[i] - step.q![i]),
                            `q[${i}] step ${stepIdx - 1} (${g.phase})`).toBeLessThan(Q_TOL);
                    }
                    expect(d.chosen, `choice at step ${stepIdx - 1} (${g.phase})`).toBe(step.chosen);

                    if (step.dtype === D_BID) {
                        g = applyAction(g, { type: 'BID', seat, bid: step.chosen === PASS ? 'pass' : step.chosen }, 0);
                    } else {
                        g = applyAction(g, { type: 'PLAY_CARD', seat, card: intToCard(step.chosen) }, 0);
                    }
                } else if (phase === 'widow') {
                    // scripted in the arena and in the live bots: trump intent
                    // (one fixture step), then the heuristic go-down (four)
                    const seat = g.turn!;
                    const intent = nextStep();
                    expect(intent.dtype).toBe(D_TRUMP);
                    const trump = bestTrumpSuit(g.hands[seat]);
                    expect(suitToInt(trump)).toBe(intent.chosen);

                    const picks = [0, 1, 2, 3].map(() => nextStep());
                    picks.forEach((p) => expect(p.dtype).toBe(D_DISCARD));
                    const goDown = chooseGoDown(g.hands[seat], trump, PERSONALITIES.basic.goDownBuryPenalty);
                    expect(goDown.map(cardToInt).sort((a, b) => a - b))
                        .toEqual(picks.map((p) => p.chosen).sort((a, b) => a - b));

                    g = applyAction(g, { type: 'SELECT_GODOWN', seat, cards: picks.map((p) => intToCard(p.chosen)) }, 0);
                    g = applyAction(g, { type: 'SELECT_TRUMP', seat, suit: SUITS[intent.chosen] }, 0);
                } else {
                    throw new Error(`unexpected phase ${phase}`);
                }
            }
            expect(safety).toBeGreaterThan(0);

            expect(stepIdx).toBe(f.steps.length);
            expect(deckIdx).toBe(f.decks.length);
            expect([g.scores.A, g.scores.B]).toEqual(f.finalScores);
            expect(g.handHistory.length).toBe(f.handsPlayed);
        });
    }
});
